### ISSUE TITLE
Getting "Preview" and "Select element" to work with Electron

### ISSUE THREAD

**Issue by blazkablatnik** [getuserflow/userflow-electron#1]
Hi, we have just purchased a licence and I have a problem getting "Preview" and "Select element" option working with **electron app**.

I have server setup and opened in my electron app (host: '127.0.0.1', port: 4059). I have tested it (with third-party chrome extension) and it does except connections and messages. 

But when I try to connect to it via Userflow UI, connection is never made. I see no request to local websockets and `ensureOpen()` in `TargetWindowElectronProtocol` (`FlowBuilderTargetWindow.tsx:159`) is never called and this is the only way I see a connection to local ws can be made.

Am I doing something wrong?

**Comment by sebastianseilund** [comment]
Hi there :)

Can you check 2 things:

1. That your Electron app is calling `startDevServer` like the README describes
2. That you've selected "Electron app" here:

![CleanShot 2021-01-08 at 12 09 02@2x](https://user-images.githubusercontent.com/744493/104059521-58bcf200-51aa-11eb-9989-86a31955aee7.png)

If neither of those help, then please contact us on the https://getuserflow.com Live-chat and we can help debug.

**Comment by sebastianseilund** [comment]
We found out on the live-chat that it was because Userflow was waiting for the Userflow Chrome Extension to be installed. Investigating whether that's necessary when using Electron...
